import { Alert } from "./components/ui/alert";
import { Slider } from "./components/ui/slider";
import { Label } from "./components/ui/label";
import { Checkbox } from "./components/ui/checkbox";
import { Disclosure, DisclosureTrigger, DisclosureContent } from "./components/ui/disclosure";
import { NativeSelect, NativeSelectOption } from "./components/ui/native-select";
import { Button } from "./components/ui/button";
import { Textarea } from "./components/ui/textarea";
import { Input } from "./components/ui/input";
import { useEffect, useRef, useState } from "react";
import { assemblyInputSchema } from "@benchledger/api-contract";
import type { AssemblyGeometry, AssemblyInput, AssemblyInspection, AssemblyPart, AssemblyRead, AssemblySource, AssemblyVector, ProjectAssembly } from "@benchledger/api-contract";
import type { Project } from "./domain";
import { workflowCommandKey, workflowRequest } from "./api";
import { mutationValue, revisionWorkflowPath, useWorkflowCommand, useWorkflowRead } from "./workflow-ui";
import { useUnsavedWork } from "./unsaved-work";
import "./assembly.css";
import { DeferredAssemblyCanvas as Canvas } from "./deferred-views";
const toDraft = (saved: ProjectAssembly): AssemblyInput => ({ expectedVersion: saved.version, name: saved.name, sources: saved.sources, parts: saved.parts, steps: saved.steps, notes: saved.notes });
export function AssemblyWorkspace({ project, onFiles }: { project: Project; onFiles(): void }) {
  const root = project.serverRevisionId ? `${revisionWorkflowPath(project.id, project.serverRevisionId)}/assembly` : undefined;
  const read = useWorkflowRead<AssemblyRead>(root), command = useWorkflowCommand();
  const [draft, setDraft] = useState<AssemblyInput>(), [baseline, setBaseline] = useState("");
  const [geometry, setGeometry] = useState<AssemblyGeometry[]>([]), [warnings, setWarnings] = useState<string[]>([]), [error, setError] = useState<string>();
  const [loading, setLoading] = useState(false), [editing, setEditing] = useState(false), [choosing, setChoosing] = useState(false), [sources, setSources] = useState<AssemblySource[]>([]);
  const [selected, setSelected] = useState<string>(), [hidden, setHidden] = useState(new Set<string>()), [explosion, setExplosion] = useState(0), [view, setView] = useState<"iso" | "front" | "rear">("iso"), [fit, setFit] = useState(0), [panel, setPanel] = useState<"parts" | "steps">("parts");
  const [query, setQuery] = useState("");
  const workspace = useRef<HTMLElement>(null);
  const sequence = useRef(0), initialised = useRef<string | undefined>(undefined), live = useRef(true);
  useEffect(() => { live.current = true; return () => { live.current = false; sequence.current++; }; }, []);
  const dirty = Boolean(draft && JSON.stringify(draft) !== baseline);
  useUnsavedWork(dirty, "assembly", command.busy || command.uncertain);
  const locked = command.busy || command.uncertain || project.status === "archived";
  const inspect = async (input: AssemblySource[], existing?: AssemblyInput) => {
    if (!root) return; const request = ++sequence.current; setLoading(true); setError(undefined);
    try {
      const result = await workflowRequest<AssemblyInspection>(`${root}/inspect`, "POST", { sources: input });
      if (!live.current || request !== sequence.current) return;
      if (!result.parts.length || !result.geometry.length) throw new Error("No viewable parts were returned.");
      const next = existing ?? { expectedVersion: draft?.expectedVersion ?? read.data?.assembly?.version ?? 0, name: `${project.name} assembly`, sources: result.sources, parts: result.parts, steps: [], notes: "" };
      setGeometry(result.geometry); setDraft(next); setWarnings(result.warnings); setChoosing(false); setSelected(undefined); setQuery(""); setHidden(new Set()); setFit(v => v + 1);
      if (existing) setBaseline(JSON.stringify(existing)); else { setBaseline(""); setEditing(false); requestAnimationFrame(() => workspace.current?.scrollIntoView?.({ block: "start" })); }
    } catch (failure) { if (live.current && request === sequence.current) setError(failure instanceof Error ? failure.message : "Could not inspect these files."); }
    finally { if (live.current && request === sequence.current) setLoading(false); }
  };
  useEffect(() => {
    const saved = read.data?.assembly;
    if (!saved || initialised.current === saved.contentSha256) return;
    initialised.current = saved.contentSha256; const next = toDraft(saved); setDraft(next); setBaseline(JSON.stringify(next)); setSources(next.sources); void inspect(next.sources, next);
  }, [read.data]);
  const updatePart = (patch: Partial<AssemblyPart>) => setDraft(current => current ? { ...current, parts: current.parts.map(p => p.id === selected ? { ...p, ...patch } : p) } : current);
  const save = async () => {
    if (!root || !draft) return; setError(undefined);
    const parsed = assemblyInputSchema.safeParse(draft); if (!parsed.success) { setError(parsed.error.issues.map(i => i.message).join("; ")); return; }
    try {
      const saved = await command.execute(root, "PUT", parsed.data, raw => { const value = mutationValue<ProjectAssembly>(raw, ["id", "version", "sources", "parts", "contentSha256"]); if (value.projectRevisionId !== project.serverRevisionId || value.version !== draft.expectedVersion + 1) throw new Error("The service did not confirm this assembly revision."); return value; });
      if (!live.current) return; const next = toDraft(saved); setDraft(next); setBaseline(JSON.stringify(next)); initialised.current = saved.contentSha256; setEditing(false); read.reload();
    } catch { /* Keep the draft and stable retry key. */ }
  };
  const files = (project.allArtifacts ?? project.artifacts).filter(f => f.status !== "superseded" && /\.(glb|stl|step|stp|kicad_pcb)$/iu.test(f.name) && (f.projectRevisionId === project.serverRevisionId || f.workItemId && f.workItemRevisionId));
  const visibleParts = draft?.parts.filter(p => `${p.name} ${p.group}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())) ?? [];
  const sourceFor = (file: typeof files[number]): AssemblySource => ({ artifactId: file.id, sha256: file.hash, upAxis: /\.glb$/iu.test(file.name) ? "y" : "z", unit: /\.glb$/iu.test(file.name) ? "metre" : "millimetre" });
  const part = draft?.parts.find(p => p.id === selected);
  const toggle = (ids: string[], visible: boolean) => setHidden(current => { const next = new Set(current); ids.forEach(id => visible ? next.delete(id) : next.add(id)); return next; });
  const preset = (value: number, direction: typeof view = "iso") => { setExplosion(value); setView(direction); setFit(v => v + 1); };
  if (!root) return <section className="assembly-empty"><h2>Assembly explorer</h2><p>Create a project revision to attach an assembly.</p></section>;
  return <section ref={workspace} className="assembly-workspace" aria-label="Assembly explorer">
    <header className="assembly-heading"><div><h2>{draft?.name ?? "See how it fits together"}</h2><p>{draft ? `${draft.parts.length} parts · ${dirty ? "Unsaved changes" : `Saved version ${draft.expectedVersion}`}` : "Explore your model, separate its parts and keep a build guide alongside it."}</p></div>
      <div className="assembly-heading-actions">{draft && !locked && <Button variant="outline" type="button" className="button button-secondary" disabled={loading} onClick={() => setEditing(!editing)}>{editing ? "Done editing" : "Edit assembly"}</Button>}
      {draft && (editing || dirty) && <Button variant="default" type="button" className="button button-primary" disabled={command.busy || loading || project.status === "archived"} onClick={() => void save()}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged assembly" : "Save assembly"}</Button>}
      </div>
    </header>
    {(error || command.error || read.error) && <Alert asChild><div className="assembly-message" role="alert"><p>{error ?? command.error ?? read.error}</p>{!command.uncertain && <Button variant="ghost" type="button" onClick={() => { sequence.current++; setLoading(false); setDraft(undefined); setGeometry([]); setBaseline(""); setError(undefined); command.clear(); initialised.current = undefined; read.reload(); }}>Discard edits and reload saved assembly</Button>}</div></Alert>}
    {(loading || read.loading) && <p className="assembly-message" role="status">Reading model parts…</p>}
    {(!draft || choosing) && !read.loading && <div className="assembly-empty"><h3>{draft ? "Choose replacement source files" : "Start with your model"}</h3><p>Choose KiCad PCB, STEP, GLB or STL files from this revision or its project workstreams. Separate STL files become individual parts. KiCad board coordinates are fixed millimetres / Z up. Other CAD formats can be exported to STEP or GLB.</p>
      {!files.length ? <Button variant="default" type="button" className="button button-primary" onClick={onFiles}>Add model files in Files</Button> : <>
        <fieldset className="assembly-file-picker" disabled={loading || locked}><legend>Model files</legend><div className="assembly-file-actions"><span>{sources.length} selected · up to 16 files</span><Button variant="ghost" type="button" disabled={files.length > 16 || sources.length === files.length} onClick={() => setSources(files.map(file => sources.find(source => source.artifactId === file.id) ?? sourceFor(file)))}>Select all files</Button><Button variant="ghost" type="button" disabled={!sources.length} onClick={() => setSources([])}>Clear selection</Button></div><div className="assembly-source-list">{files.map(file => { const source = sources.find(s => s.artifactId === file.id); return <div className="assembly-source" key={file.id}><Label><Checkbox  checked={Boolean(source)} disabled={!source && sources.length >= 16} onCheckedChange={checked => setSources(current => checked === true ? [...current, sourceFor(file)] : current.filter(s => s.artifactId !== file.id))} />{file.name}</Label>{source && <Disclosure className="assembly-coordinates"><DisclosureTrigger>Coordinates</DisclosureTrigger><DisclosureContent><Label>Units <NativeSelect aria-label={`Coordinate units for ${file.name}`} disabled={/\.(st(e)?p|kicad_pcb)$/iu.test(file.name)} value={source.unit} onChange={e => setSources(current => current.map(s => s.artifactId === file.id ? { ...s, unit: e.target.value as AssemblySource["unit"] } : s))}>{["millimetre", "centimetre", "metre", "inch"].map(u => <NativeSelectOption key={u} value={u}>{u}</NativeSelectOption>)}</NativeSelect><span>Up axis</span><NativeSelect aria-label={`Up axis for ${file.name}`} disabled={/\.kicad_pcb$/iu.test(file.name)} value={source.upAxis} onChange={e => setSources(current => current.map(s => s.artifactId === file.id ? { ...s, upAxis: e.target.value as "y" | "z" } : s))}><NativeSelectOption value="z">Z up (CAD)</NativeSelectOption><NativeSelectOption value="y">Y up (glTF)</NativeSelectOption></NativeSelect>{/\.st(e)?p$/iu.test(file.name) && <small>STEP uses its declared units.</small>}</Label></DisclosureContent></Disclosure>}</div>; })}</div></fieldset>
        <p>Coordinates use each format’s defaults. Adjust them per file if needed, then check the model dimensions.</p>
        <Button variant="default" type="button" className="button button-primary" disabled={loading || locked || !sources.length || sources.length > 16} onClick={() => void inspect(sources)}>{draft ? "Replace draft from these files" : "Open assembly"}</Button>
        <Button variant="ghost" type="button" className="button button-quiet" onClick={onFiles}>Add another file</Button>{choosing && <Button variant="ghost" type="button" disabled={loading} onClick={() => setChoosing(false)}>Keep current assembly</Button>}
      </>}
    </div>}
    {draft && !choosing && <>
      {draft.sources.length > 1 && <p className="assembly-placement-note">Parts keep their exported positions. Use Edit assembly to adjust placement if separate files overlap.</p>}
      <div className="assembly-layout"><div className="assembly-stage">
        <div className="assembly-toolbar" role="group" aria-label="Assembly views"><Button variant="ghost" type="button" aria-pressed={explosion === 0} onClick={() => preset(0)}>Assembled</Button><Button variant="ghost" type="button" aria-pressed={explosion === 100} onClick={() => preset(100)}>Exploded</Button><Button variant="ghost" type="button" onClick={() => preset(explosion, "rear")}>Rear</Button><Button variant="ghost" type="button" onClick={() => { setHidden(new Set()); setFit(v => v + 1); }}>Show all</Button><Button variant="ghost" type="button" onClick={() => setFit(v => v + 1)}>Fit view</Button></div>
        {geometry.length > 0 ? <Canvas geometry={geometry} parts={draft.parts} hidden={hidden} selected={selected} explosion={explosion} view={view} fit={fit} onSelect={setSelected} /> : <div className="assembly-canvas"><p>The parts guide is available while the model loads.</p></div>}
        <p className="assembly-gestures">Drag to rotate · scroll or pinch to zoom · click a part to inspect</p>
        <div className="assembly-slider"><Label htmlFor="assembly-explosion">Pull the assembly apart <output>{explosion}%</output></Label><Slider id="assembly-explosion" aria-label="Assembly separation" min={0} max={100} value={[explosion]} onValueChange={values => setExplosion(values[0] ?? 0)} onPointerUp={() => setFit(v => v + 1)} onKeyUp={() => setFit(v => v + 1)} /><p>Separation shows relationships, not a verified removal path.</p></div>
      </div><aside className="assembly-guide" aria-label="Parts and build guide">
        <div className="assembly-guide-switch"><Button variant="ghost" type="button" aria-pressed={panel === "parts"} onClick={() => setPanel("parts")}>Parts & details</Button><Button variant="ghost" type="button" aria-pressed={panel === "steps"} onClick={() => setPanel("steps")}>Build order</Button></div>
        {panel === "parts" ? <><Label className="assembly-search">Find a part<Input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search names or groups" /></Label><div className="assembly-parts" role="region" aria-label="Model parts" tabIndex={0}>{visibleParts.length === 0 && <p>No matching parts.</p>}{[...new Set(visibleParts.map(p => p.group))].map(group => <div key={group}>{group && <Label className="assembly-group"><Checkbox  checked={draft.parts.filter(p => p.group === group).some(p => !hidden.has(p.id))} onCheckedChange={checked => toggle(draft.parts.filter(p => p.group === group).map(p => p.id), checked === true)} />{group}</Label>}{visibleParts.filter(p => p.group === group).map(p => <div className={`assembly-part ${selected === p.id ? "selected" : ""}`} key={p.id}><Checkbox  aria-label={`Show ${p.name}`} checked={!hidden.has(p.id)} onCheckedChange={checked => toggle([p.id], checked === true)} /><Button variant="ghost" type="button" aria-pressed={selected === p.id} onClick={() => setSelected(p.id)}><span className="assembly-swatch" style={{ background: p.color }} />{p.name}</Button></div>)}</div>)}</div>
          {part ? <div className="assembly-detail"><h3>{part.name}</h3>{part.material && <p>{part.material}</p>}<p className="assembly-part-source">{files.find(file => file.id === part.artifactId)?.name}</p><p>{part.notes || "No fixing notes recorded."}</p>{part.bomLineId && <p>Requirement: {project.bom.find(b => b.id === part.bomLineId)?.label ?? "Unavailable in this revision"}</p>}<div className="assembly-actions"><Button variant="ghost" type="button" onClick={() => { setHidden(new Set(draft.parts.filter(p => p.id !== part.id).map(p => p.id))); setFit(v => v + 1); }}>Isolate part</Button><Button variant="ghost" type="button" onClick={() => { setHidden(new Set()); setSelected(undefined); setFit(v => v + 1); }}>Show all parts</Button></div>
            {editing && <fieldset disabled={locked || loading} className="assembly-edit"><legend>Edit selected part</legend><Label>Name<Input maxLength={160} value={part.name} onChange={e => updatePart({ name: e.target.value })} /></Label><Label>Group<Input maxLength={160} value={part.group} onChange={e => updatePart({ group: e.target.value })} /></Label><Label>Colour<Input type="color" value={part.color} onChange={e => updatePart({ color: e.target.value })} /></Label><Label>Material<Input maxLength={240} value={part.material} onChange={e => updatePart({ material: e.target.value })} /></Label>
              <VectorEditor label="Separation (mm)" value={part.explode} onChange={explode => updatePart({ explode })} /><VectorEditor label="Position adjustment (mm)" value={part.position} onChange={position => updatePart({ position })} /><VectorEditor label="Rotation XYZ (degrees)" value={part.rotation} onChange={rotation => updatePart({ rotation })} />
              {part.group && <Button variant="ghost" type="button" onClick={() => setDraft({ ...draft, parts: draft.parts.map(p => p.group === part.group ? { ...p, explode: [...part.explode] } : p) })}>Use this separation for group</Button>}
              <Label>Requirement<NativeSelect value={part.bomLineId ?? ""} onChange={e => setDraft({ ...draft, parts: draft.parts.map(p => { if (p.id !== part.id) return p; const { bomLineId: _old, ...rest } = p; return e.target.value ? { ...rest, bomLineId: e.target.value } : rest; }) })}><NativeSelectOption value="">No requirement linked</NativeSelectOption>{part.bomLineId && !project.bom.some(b => b.id === part.bomLineId) && <NativeSelectOption value={part.bomLineId}>Unavailable requirement</NativeSelectOption>}{project.bom.map(b => <NativeSelectOption key={b.id} value={b.id}>{b.label}</NativeSelectOption>)}</NativeSelect></Label>
              <Label>Fixing notes<Textarea rows={3} maxLength={2000} value={part.notes} onChange={e => updatePart({ notes: e.target.value })} /></Label>
              <Button variant="ghost" type="button" disabled={draft.parts.length >= 300} onClick={() => { const id = workflowCommandKey("assembly-part"); setDraft({ ...draft, parts: [...draft.parts, { ...part, id, name: `${part.name.slice(0, 150)} copy`, position: [part.position[0] + 20, part.position[1], part.position[2]] }] }); setSelected(id); }}>Add another placement</Button>
            </fieldset>}
          </div> : <div className="assembly-detail"><h3>Explore the construction</h3><p>Select a part in the model or list. Use the checkboxes to peel away layers.</p></div>}
        </> : <div className="assembly-steps">{!draft.steps.length && <p>No build steps recorded yet. Add steps to explain how the parts go together.</p>}{draft.steps.map((step, i) => <section key={step.id}><Button variant="ghost" type="button" className="assembly-step-title" onClick={() => { setHidden(new Set(draft.parts.filter(p => !step.partIds.includes(p.id)).map(p => p.id))); setSelected(step.partIds[0]); preset(55); }}><span>{String(i + 1).padStart(2, "0")}</span>{step.name}</Button><p>{step.notes}</p>{editing && <fieldset disabled={locked || loading} className="assembly-edit"><legend>Step {i + 1}</legend><Label>Step title<Input maxLength={160} value={step.name} onChange={e => setDraft({ ...draft, steps: draft.steps.map(s => s.id === step.id ? { ...s, name: e.target.value } : s) })} /></Label><Label>Instructions<Textarea maxLength={3000} value={step.notes} onChange={e => setDraft({ ...draft, steps: draft.steps.map(s => s.id === step.id ? { ...s, notes: e.target.value } : s) })} /></Label><Disclosure><DisclosureTrigger>Parts in this step ({step.partIds.length})</DisclosureTrigger><DisclosureContent>{draft.parts.map(p => <Label key={p.id}><Checkbox  checked={step.partIds.includes(p.id)} onCheckedChange={checked => setDraft({ ...draft, steps: draft.steps.map(s => s.id === step.id ? { ...s, partIds: checked === true ? [...s.partIds, p.id] : s.partIds.filter(id => id !== p.id) } : s) })} />{p.name}</Label>)}</DisclosureContent></Disclosure><Button variant="ghost" type="button" disabled={i === 0} onClick={() => { const steps = [...draft.steps]; [steps[i - 1], steps[i]] = [steps[i]!, steps[i - 1]!]; setDraft({ ...draft, steps }); }}>Move step up</Button><Button variant="ghost" type="button" onClick={() => setDraft({ ...draft, steps: draft.steps.filter(s => s.id !== step.id) })}>Remove draft step</Button></fieldset>}</section>)}{editing && <Button variant="ghost" type="button" disabled={locked || loading || draft.steps.length >= 100} onClick={() => setDraft({ ...draft, steps: [...draft.steps, { id: workflowCommandKey("assembly-step"), name: `Step ${draft.steps.length + 1}`, partIds: [selected ?? draft.parts[0]!.id], notes: "" }] })}>Add build step</Button>}</div>}
      </aside></div>
      {editing && <fieldset className="assembly-settings assembly-edit" disabled={locked || loading}><legend>Assembly details</legend><Label>Assembly name<Input maxLength={160} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></Label><Label>Assembly notes<Textarea maxLength={5000} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></Label><Button variant="ghost" type="button" onClick={() => { setSources(draft.sources); setChoosing(true); }}>Change source files</Button><p>Changing files creates a fresh draft layout and clears its build steps. Saved history is retained.</p></fieldset>}
      {!editing && draft.notes && <p className="assembly-message">{draft.notes}</p>}
      <Disclosure className="assembly-evidence"><DisclosureTrigger>Source files and viewing limits</DisclosureTrigger><DisclosureContent><ul>{[...warnings, ...(read.data?.warnings ?? [])].map((warning, i) => <li key={i}>{warning}</li>)}</ul>{draft.sources.map(source => <p key={source.artifactId}>{(project.allArtifacts ?? project.artifacts).find(f => f.id === source.artifactId)?.name ?? source.artifactId}<br /><code>{source.sha256}</code></p>)}<p>Saving changes viewing and guidance only. Source CAD, stock quantities and physical validation remain separate.</p></DisclosureContent></Disclosure>
    </>}
  </section>;
}
function VectorEditor({ label, value, onChange }: { label: string; value: AssemblyVector; onChange(value: AssemblyVector): void }) {
  return <div className="assembly-vector"><span>{label}</span><div>{["X", "Y", "Z"].map((axis, i) => <Label key={axis}>{axis}<Input aria-label={`${label} ${axis}`} type="number" step="any" min={-1e7} max={1e7} value={value[i]} onChange={e => { const next: AssemblyVector = [...value]; next[i] = Number(e.target.value); onChange(next); }} /></Label>)}</div></div>;
}
