import { useState } from "react";
import { buildPlanInputSchema } from "@benchledger/api-contract";
import type { BuildPlan, BuildPlanInput } from "@benchledger/api-contract";
import type { Project, InventoryItem } from "./domain";
import { useWorkflowRead, useWorkflowCommand, mutationValue, revisionWorkflowPath } from "./workflow-ui";
import { workflowCommandKey } from "./api";
type Part = BuildPlanInput["parts"][number];
type Plate = BuildPlanInput["plates"][number];

export function BuildPlanning({ project, items, readOnly = false }: { project: Project; items: InventoryItem[]; readOnly?: boolean }) {
  const root = project.serverRevisionId ? revisionWorkflowPath(project.id, project.serverRevisionId) : undefined;
  const source = useWorkflowRead<BuildPlan | null>(root ? `${root}/build-plan` : undefined);
  const [editing, setEditing] = useState(false), [historyOpen, setHistoryOpen] = useState(false), [cursor, setCursor] = useState<string>();
  const history = useWorkflowRead<{ data: BuildPlan[]; nextCursor?: string }>(root && historyOpen ? `${root}/build-plan/history?limit=10${cursor ? `&cursor=${cursor}` : ""}` : undefined, String(source.data?.version));
  if (!root) return <p>A connected revision is required for a build plan.</p>;
  return <section className="surface build-planning"><h2>Parts and build plates</h2><p>Plan repeated parts, plate runs, filament and time. No printer or stock is changed by a planning snapshot.</p>
    {source.loading && <p role="status">Loading build plan…</p>}{source.error && <p role="alert">{source.error}</p>}
    {editing ? <BuildEditor key={`${project.id}:${source.data?.version ?? 0}`} root={root} project={project} items={items} initial={source.data ?? null} onCancel={() => setEditing(false)} onSaved={() => { setEditing(false); source.reload(); }} /> : <>{source.data ? <PlanSummary plan={source.data} items={items} /> : <p>No multi-plate plan recorded for this revision.</p>}{!readOnly && project.status !== "archived" && <button type="button" className="button button-secondary" disabled={source.loading || Boolean(source.error)} onClick={() => setEditing(true)}>{source.data ? "Revise build plan" : "Create build plan"}</button>}</>}
    <details open={historyOpen} onToggle={(event) => setHistoryOpen(event.currentTarget.open)}><summary>Build-plan history</summary>{history.loading && <p>Loading versions…</p>}{history.error && <p role="alert">{history.error}</p>}{history.data?.data.map((plan) => <details key={plan.version}><summary>Version {plan.version}: {plan.name}</summary><PlanSummary plan={plan} items={items} /></details>)}{history.data?.nextCursor && <button type="button" className="text-button" onClick={() => setCursor(history.data!.nextCursor)}>Older versions</button>}{cursor && <button type="button" className="text-button" onClick={() => setCursor(undefined)}>Latest versions</button>}</details>
    <button type="button" className="text-button" onClick={source.reload}>Refresh build plan</button>
  </section>;
}
export function PlanSummary({ plan, items }: { plan: BuildPlan; items: InventoryItem[] }) {
  return <section><h3>{plan.name} · version {plan.version}</h3><div className="workflow-table-scroll"><table className="data-table"><caption>Part coverage</caption><thead><tr><th>Part</th><th>Required</th><th>Planned</th><th>Missing</th><th>Extra</th></tr></thead><tbody>{plan.totals.parts.map((part) => <tr key={part.id}><td>{plan.parts.find((entry) => entry.id === part.id)?.name ?? part.id}</td><td>{part.required}</td><td>{part.planned}</td><td>{part.missing}</td><td>{part.excess}</td></tr>)}</tbody></table></div>
    <p>{plan.plates.reduce((sum, plate) => sum + plate.copies, 0)} planned runs · {plan.totals.minutes} recorded minutes{plan.totals.timeComplete ? "" : " (some estimates missing)"}</p>{plan.totals.materialGrams.map((entry) => <p key={entry.itemId}>{items.find((item) => item.id === entry.itemId)?.name ?? entry.itemId}: {entry.grams} g planned</p>)}
    <details><summary>Planning checks and file evidence</summary><ul>{plan.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul><p className="identifier-value">Snapshot: {plan.contentSha256}</p>{plan.artifactBasis.map((file) => <p className="identifier-value" key={file.id}>{file.id}: {file.sha256}</p>)}</details>
  </section>;
}

export function BuildEditor({ project, items, initial, root, onCancel, onSaved }: { project: Project; items: InventoryItem[]; initial: BuildPlan | null; root: string; onCancel(): void; onSaved(): void }) {
  const [draft, setDraft] = useState<BuildPlanInput>(() => initial ? { expectedVersion: initial.version, name: initial.name, parts: initial.parts, plates: initial.plates, ...(initial.notes ? { notes: initial.notes } : {}) } : { expectedVersion: 0, name: `${project.name} build plan`, parts: [], plates: [] });
  const [review, setReview] = useState<BuildPlanInput>(), [error, setError] = useState<string>();
  const command = useWorkflowCommand();
  const updatePart = (index: number, patch: Partial<Part>) => setDraft((value) => ({ ...value, parts: value.parts.map((part, i) => i === index ? { ...part, ...patch } : part) }));
  const updatePlate = (index: number, patch: Partial<Plate>) => setDraft((value) => ({ ...value, plates: value.plates.map((plate, i) => i === index ? { ...plate, ...patch } : plate) }));
  const inspect = () => { const parsed = buildPlanInputSchema.safeParse(draft); if (!parsed.success) { setError(parsed.error.issues.map((issue) => `${issue.path.join(".")}: ${issue.message}`).join("\n")); return; } setError(undefined); setReview(parsed.data); };
  const save = async () => { if (!review) return; try { await command.execute(`${root}/build-plan`, "PUT", review, (value) => { const result = mutationValue<BuildPlan>(value, ["id", "version", "contentSha256", "totals"]); if (result.projectRevisionId !== project.serverRevisionId || result.version !== review.expectedVersion + 1) throw new Error("The server did not confirm the planning snapshot."); return result; }); onSaved(); } catch { /* retain the exact reviewed draft */ } };
  if (review) return <section className="workflow-review"><h3>Review build plan</h3><p>{review.parts.length} parts · {review.plates.length} plate layouts · {review.plates.reduce((sum, plate) => sum + plate.copies, 0)} planned runs</p>{review.plates.map((plate) => <p key={plate.id}>{plate.name}: {plate.copies} runs, with {plate.parts.map((part) => `${part.quantity} × ${review.parts.find((entry) => entry.id === part.partId)?.name}`).join(", ")} per run.</p>)}<p>This records planning intent, not available stock, validated geometry or a completed print.</p>{command.error && <p role="alert">{command.error}</p>}<div className="dialog-actions"><button type="button" className="button button-quiet" disabled={command.busy || command.uncertain} onClick={() => setReview(undefined)}>Back to build draft</button><button type="button" className="button button-primary" disabled={command.busy} onClick={() => { void save(); }}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged plan" : "Save planning snapshot"}</button></div></section>;
  const files = (project.allArtifacts ?? project.artifacts).filter((file) => file.workItemRevisionId || file.projectRevisionId === project.serverRevisionId);
  return <section className="workflow-form"><label className="form-field"><span>Build plan name</span><input value={draft.name} maxLength={240} onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))} /></label>
    <h3>Required parts</h3>{draft.parts.map((part, index) => <div className="intake-row" key={part.id}><label className="form-field"><span>Part name</span><input aria-label={`Build part ${index + 1} name`} value={part.name} maxLength={240} onChange={(event) => updatePart(index, { name: event.target.value })} /></label><label className="form-field"><span>Total required</span><input aria-label={`Build part ${index + 1} quantity`} type="number" min="1" step="1" value={part.quantity} onChange={(event) => updatePart(index, { quantity: Number(event.target.value) })} /></label>
      <label className="form-field"><span>Exact revision file</span><select aria-label={`Build part ${index + 1} file`} value={part.artifactId ?? ""} onChange={(event) => { const file = files.find((entry) => entry.id === event.target.value); updatePart(index, { artifactId: file?.id, workItemId: file?.workItemId, workItemRevisionId: file?.workItemRevisionId }); }}><option value="">Not attached</option>{files.map((file) => <option key={file.id} value={file.id}>{file.name} · {file.revision}</option>)}</select></label>
      <button type="button" className="text-button" onClick={() => setDraft((value) => ({ ...value, parts: value.parts.filter((entry) => entry.id !== part.id), plates: value.plates.map((plate) => ({ ...plate, parts: plate.parts.filter((entry) => entry.partId !== part.id) })) }))}>Remove draft part {index + 1}</button></div>)}
    <button type="button" className="button button-secondary" disabled={draft.parts.length >= 100} onClick={() => setDraft((value) => ({ ...value, parts: [...value.parts, { id: workflowCommandKey("part"), name: "", quantity: 1 }] }))}>Add build part</button>
    <h3>Plate layouts</h3>{project.fabricationRoute !== "printed" && <p>Use a printed build approach to add plates. Other fabrication work can be tracked as workstreams.</p>}
    {draft.plates.map((plate, index) => <PlateEditor key={plate.id} plate={plate} index={index} parts={draft.parts} project={project} items={items} onChange={(patch) => updatePlate(index, patch)} onRemove={() => setDraft((value) => ({ ...value, plates: value.plates.filter((entry) => entry.id !== plate.id) }))} />)}
    <button type="button" className="button button-secondary" disabled={draft.plates.length >= 100 || !draft.parts.length || project.fabricationRoute !== "printed"} onClick={() => setDraft((value) => ({ ...value, plates: [...value.plates, { id: workflowCommandKey("plate"), name: `Plate ${value.plates.length + 1}`, copies: 1, parts: [{ partId: value.parts[0]!.id, quantity: 1 }], materials: [] }] }))}>Add plate layout</button>
    <label className="form-field"><span>Build planning notes</span><textarea rows={3} maxLength={5000} value={draft.notes ?? ""} onChange={(event) => setDraft((value) => ({ ...value, notes: event.target.value }))} /></label>
    {error && <p role="alert" className="form-error workflow-error">{error}</p>}<div className="dialog-actions"><button type="button" className="button button-quiet" onClick={onCancel}>Cancel build draft</button><button type="button" className="button button-primary" onClick={inspect}>Review build plan</button></div>
  </section>;
}

function PlateEditor({ plate, index, parts, project, items, onChange, onRemove }: { plate: Plate; index: number; parts: Part[]; project: Project; items: InventoryItem[]; onChange(patch: Partial<Plate>): void; onRemove(): void }) {
  const changeMaterial = (at: number, patch: Partial<Plate["materials"][number]>) => onChange({ materials: plate.materials.map((entry, i) => i === at ? { ...entry, ...patch } : entry) });
  return <details className="plate-editor" open><summary>Plate {index + 1}: {plate.name}</summary><div className="correction-fields">
    <label className="form-field"><span>Plate name</span><input aria-label={`Plate ${index + 1} name`} maxLength={240} value={plate.name} onChange={(event) => onChange({ name: event.target.value })} /></label>
    <label className="form-field"><span>Identical runs</span><input aria-label={`Plate ${index + 1} runs`} type="number" min="1" step="1" value={plate.copies} onChange={(event) => onChange({ copies: Number(event.target.value) })} /></label>
    <label className="form-field"><span>Owned printer</span><select aria-label={`Plate ${index + 1} printer`} value={plate.printerItemId ?? ""} onChange={(event) => onChange({ printerItemId: event.target.value || undefined, buildConfigurationId: undefined })}><option value="">Decide later</option>{items.filter((item) => item.category === "Printers").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    {project.buildConfigSnapshot?.printerItemId === plate.printerItemId && <label className="check-field"><input type="checkbox" checked={Boolean(plate.buildConfigurationId)} onChange={(event) => onChange({ buildConfigurationId: event.target.checked ? project.buildConfigSnapshot?.id : undefined })} /><span>Link this revision's recorded printer setup</span></label>}
    <h4>Parts on one plate</h4>{parts.map((part) => <label className="form-field" key={part.id}><span>{part.name || "Unnamed part"}</span><input aria-label={`Plate ${index + 1} quantity ${part.name}`} type="number" min="0" step="1" value={plate.parts.find((entry) => entry.partId === part.id)?.quantity ?? 0} onChange={(event) => { const quantity = Number(event.target.value); onChange({ parts: [...plate.parts.filter((entry) => entry.partId !== part.id), ...(quantity > 0 ? [{ partId: part.id, quantity }] : [])] }); }} /></label>)}
    <h4>Materials for one run</h4>{plate.materials.map((material, at) => <section className="material-editor" key={at}>
      <label className="form-field"><span>Filament spool</span><select aria-label={`Plate ${index + 1} material ${at + 1}`} value={material.itemId} onChange={(event) => changeMaterial(at, { itemId: event.target.value })}><option value="">Select owned filament</option>{items.filter((item) => item.category === "Filament" && item.unit === "g").map((item) => <option key={item.id} value={item.id}>{[item.name, item.variant, item.location].filter(Boolean).join(" · ")}</option>)}</select></label>
      <label className="form-field"><span>Grams per run</span><input type="number" min="0.01" step="any" value={material.grams} onChange={(event) => changeMaterial(at, { grams: Number(event.target.value) })} /></label>
      <label className="form-field"><span>Material role</span><select aria-label={`Plate ${index + 1} material role ${at + 1}`} value={material.role} onChange={(event) => changeMaterial(at, { role: event.target.value as typeof material.role })}><option value="model">Model</option><option value="support">Support</option><option value="interface">Support interface</option></select></label>
      <label className="form-field"><span>Nozzle side</span><select aria-label={`Plate ${index + 1} material side ${at + 1}`} value={material.side} onChange={(event) => changeMaterial(at, { side: event.target.value as typeof material.side })}>{["unspecified", "single", "left", "right"].map((value) => <option key={value}>{value}</option>)}</select></label>
      <button type="button" className="text-button" onClick={() => onChange({ materials: plate.materials.filter((_, i) => i !== at) })}>Remove material estimate</button>
    </section>)}
    <button type="button" className="button button-quiet" disabled={plate.materials.length >= 16} onClick={() => onChange({ materials: [...plate.materials, { itemId: "", grams: 1, role: "model", side: "unspecified" }] })}>Add material estimate</button>
    <label className="form-field"><span>Minutes per run, optional</span><input type="number" min="0.1" step="any" value={plate.minutes ?? ""} onChange={(event) => onChange({ minutes: event.target.value === "" ? undefined : Number(event.target.value) })} /></label>
    <button type="button" className="text-button" onClick={onRemove}>Remove plate {index + 1} from draft</button>
  </div></details>;
}
