import { useUnsavedWork } from "./unsaved-work";
import { useCallback, useEffect, useState } from "react";
import { requirementOfferSchema, offerChoiceSchema } from "@benchledger/api-contract";
import type { BomLine, RequirementOffer, OfferChoice, RequirementOfferEstimate } from "@benchledger/api-contract";
import type { Project } from "./domain";
import { useWorkflowRead, useWorkflowCommand, mutationValue, quotedMoney, quotedMinor, revisionWorkflowPath } from "./workflow-ui";
interface SourcingRow { line: BomLine; decision: string; missingQuantity: number; offers: RequirementOffer[]; choice: OfferChoice | null; estimate: RequirementOfferEstimate }
interface SourcingPage { data: SourcingRow[]; total: number; revisionTotal?: number; nextCursor?: string; totals: Record<string, { knownMinor: number; shippingComplete: boolean; taxesComplete: boolean }>; notice: string }
export function RequirementSourcing({ project, readOnly = false, onPlan }: { project: Project; readOnly?: boolean; onPlan?: (() => void) | undefined }) {
  const [filter, setFilter] = useState<"source" | "review" | "all" | "optional">("source");
  const [query, setQuery] = useState("");
  const [cursor, setCursor] = useState<string>(), [previous, setPrevious] = useState<(string | undefined)[]>([]), [draftFor, setDraftFor] = useState<string>();
  const root = project.serverRevisionId ? revisionWorkflowPath(project.id, project.serverRevisionId) : undefined;
  const parameters = new URLSearchParams({ limit: "20", filter, ...(query.trim() ? { query: query.trim() } : {}), ...(cursor ? { cursor } : {}) });
  const source = useWorkflowRead<SourcingPage>(root ? `${root}/sourcing?${parameters}` : undefined, JSON.stringify(project.bom.map((line) => [line.id, line.version])));
  const [saved, setSaved] = useState(false);
  const [pendingSelections, setPendingSelections] = useState<Set<string>>(() => new Set());
  const selectionState = useCallback((id: string, pending: boolean) => setPendingSelections((current) => {
    if (current.has(id) === pending) return current;
    const next = new Set(current); if (pending) next.add(id); else next.delete(id); return next;
  }), []);
  const selectionBlocked = pendingSelections.size > 0;

  if (!root) return <p>Supplier quotes require a connected project revision.</p>;
  const visibleRows = source.data?.data ?? [];
  const refreshBlocked = draftFor !== undefined || source.loading || selectionBlocked;
  const canWrite = !readOnly && project.status !== "archived" && !source.loading && !source.error;
  return <section className="surface requirement-sourcing" aria-label="Requirement sourcing">
    <div className="workflow-section-heading"><div><span className="eyebrow">Shopping list</span><h2>Supplier quotes for this project</h2></div>{onPlan && <button type="button" className="button button-quiet" onClick={onPlan}>Back to plan</button>}</div>
    <p>Record quotes for missing stock. Check each quote before selection. No purchase is made.</p>
    <div className="sourcing-view-controls"><div role="group" aria-label="Sourcing view">{([["source", "Needs sourcing"], ["review", "Needs review"], ["optional", "Optional"], ["all", "All requirements"]] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={filter === value} disabled={draftFor !== undefined || selectionBlocked} onClick={() => { setFilter(value); setCursor(undefined); setPrevious([]); }}>{label}</button>)}</div><label className="field-search"><input aria-label="Search quote requirements" placeholder="Find a requirement or supplier" value={query} disabled={draftFor !== undefined || selectionBlocked} onChange={(event) => { setQuery(event.target.value.slice(0, 200)); setCursor(undefined); setPrevious([]); }} /></label></div>
    <p className="form-hint">Search covers all requirements in this revision. Cost totals do not change with the filter.</p>
    {saved && <p role="status" className="form-success">Quote saved.{source.error ? " The list could not refresh. Retry the read, not the save." : ""}</p>}
    {source.loading && <p role="status">Loading requirement quotes…</p>}{source.error && <p role="alert">{source.error}{source.data ? " Previous records remain visible. Refresh before making another change." : ""}</p>}
    {source.data && <><div className="sourcing-totals">{Object.entries(source.data.totals).length ? Object.entries(source.data.totals).map(([currency, total]) => <p key={currency}><strong>{quotedMoney(total.knownMinor, currency)}</strong> · {total.shippingComplete ? "recorded shipping included" : "shipping incomplete"} · {total.taxesComplete ? "tax included" : "tax not fully confirmed"}</p>) : <p>No current quotes selected for the estimate.</p>}</div>
      <p className="sourcing-results-count" role="status">{source.data.total} matching {source.data.total === 1 ? "requirement" : "requirements"} · {source.data.revisionTotal ?? source.data.total} in the full revision</p>
      {!visibleRows.length && !source.loading && !source.error && <div className="sourcing-empty"><strong>{filter === "source" ? "No source gaps match this view" : "No requirements match this view"}</strong><p>Change the filter or search to review other requirements.</p><button type="button" className="button button-secondary" onClick={() => { setFilter("all"); setQuery(""); setCursor(undefined); setPrevious([]); }}>Show all quote requirements</button></div>}
      <div className="sourcing-register">{visibleRows.map((row) => <article className={`sourcing-requirement ${row.offers.length ? "has-quotes" : "no-quotes"}`} aria-label={`Quotes for ${row.line.name}`} key={row.line.id}>
        <div className="sourcing-row-summary"><div><h3>{row.line.name}</h3><p>{row.line.requiredQuantity} {row.line.unit} required · {row.missingQuantity} unfilled · {row.offers.length} {row.offers.length === 1 ? "quote" : "quotes"}</p></div><span className={`status-pill tone-${row.line.optional ? "neutral" : row.decision === "ready" ? "good" : row.decision === "source" ? "bad" : row.decision === "check" ? "warn" : "info"}`}>{row.line.optional ? "Optional" : row.decision === "source" ? "Source" : row.decision === "check" ? "Check" : row.decision === "ready" ? "Ready" : "Decide"}</span>
          {!readOnly && project.status !== "archived" && draftFor !== row.line.id && <button type="button" className="button button-secondary" disabled={!canWrite || draftFor !== undefined || selectionBlocked} onClick={() => { setSaved(false); setDraftFor(row.line.id); }} aria-label={`Record quote for ${row.line.name}`}>Record quote</button>}
        </div>
        {row.estimate.status === "estimated" ? <p className="estimate-summary">{row.estimate.packages} packs supply {row.estimate.partsSupplied} {row.line.unit} · {quotedMoney(row.estimate.totalMinor!, row.estimate.currency!)} known cost</p> : row.offers.length > 0 && <p className="form-hint">{row.estimate.reason}</p>}
        {row.offers.map((offer) => <QuoteCard key={offer.id} offer={offer} row={row} root={root} readOnly={!canWrite || draftFor !== undefined || selectionBlocked && !pendingSelections.has(offer.id)} onPending={selectionState} onSaved={source.reload} />)}
        {draftFor === row.line.id && <QuoteForm line={row.line} root={root} onSaved={() => { setDraftFor(undefined); setSaved(true); source.reload(); }} onCancel={() => setDraftFor(undefined)} />}
      </article>)}</div>
      <div className="workflow-pagination"><button type="button" className="button button-quiet" disabled={!previous.length || refreshBlocked} onClick={() => { setCursor(previous.at(-1)); setPrevious((all) => all.slice(0, -1)); }}>Previous requirements</button><span>{visibleRows.length} shown · {source.data.total} matches</span><button type="button" className="button button-quiet" disabled={!source.data.nextCursor || refreshBlocked} onClick={() => { setPrevious((all) => [...all, cursor]); setCursor(source.data!.nextCursor); }}>Next requirements</button></div>
    </>}
    <button type="button" className="text-button" disabled={refreshBlocked} onClick={source.reload}>Refresh supplier quotes</button>
  </section>;
}
function QuoteCard({ offer, row, root, readOnly, onSaved, onPending }: { offer: RequirementOffer; row: SourcingRow; root: string; readOnly: boolean; onSaved(): void; onPending(id: string, pending: boolean): void }) {
  const [confirmed, setConfirmed] = useState(false); const command = useWorkflowCommand();
  useUnsavedWork(command.uncertain, "quote selection", command.busy || command.uncertain);
  useEffect(() => { onPending(offer.id, command.busy || command.uncertain); return () => onPending(offer.id, false); }, [offer.id, command.busy, command.uncertain, onPending]);
  const selected = row.choice?.offerId === offer.id, current = selected && row.choice?.bomLineVersion === row.line.version;
  const choose = async () => { try { await command.execute(`${root}/offer-choice`, "PUT", { bomLineId: row.line.id, offerId: selected && current ? null : offer.id, expectedVersion: row.choice?.version ?? 0, expectedBomLineVersion: row.line.version, confirmedFit: confirmed }, (value) => offerChoiceSchema.parse(mutationValue(value, ["id", "version"]))); onSaved(); } catch { /* state retained for explicit retry */ } };
  return <div className={`quote-card ${selected ? "is-selected" : ""}`}><strong>{offer.supplier}: {offer.title}</strong><p>{quotedMoney(offer.priceMinor, offer.currency)} per pack of {offer.packageQuantity} {offer.packageUnit} · shipping {offer.shippingMinor === undefined ? "not recorded" : quotedMoney(offer.shippingMinor, offer.currency)} · tax {offer.taxIncluded}</p><p>Observed {offer.observedAt.slice(0,10)} · review after {offer.validForDays} days</p>{offer.notes && <p>{offer.notes}</p>}<a href={offer.url} target="_blank" rel="noreferrer noopener">Open recorded supplier source</a>
    {selected && <p>{current ? "Selected for estimate" : "Selected quote needs renewed review because the requirement changed"}</p>}
    {!readOnly && <div className="quote-review-actions">{(!selected || !current) && <label className="check-field"><input type="checkbox" checked={confirmed} disabled={command.busy || command.uncertain} onChange={(event) => setConfirmed(event.target.checked)} /><span>I checked that this quoted item meets the current requirement</span></label>}<button type="button" className="button button-quiet" disabled={command.busy || (!current && !confirmed)} onClick={() => { void choose(); }}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged selection" : current ? "Clear quote selection" : "Use reviewed quote"}</button></div>}
    {command.error && <p role="alert" className="form-error">{command.error}</p>}
  </div>;
}
export function QuoteForm({ line, root, onSaved, onCancel }: { line: BomLine; root: string; onSaved(): void; onCancel(): void }) {
  const [supplier, setSupplier] = useState(""), [title, setTitle] = useState(line.name), [url, setUrl] = useState("");
  const [quantity, setQuantity] = useState("1"), [unit, setUnit] = useState(line.unit), [price, setPrice] = useState(""), [currency, setCurrency] = useState("EUR"), [shipping, setShipping] = useState("");
  const [initialObservedAt] = useState(() => new Date().toISOString().slice(0,10));
  const [tax, setTax] = useState("unknown"), [observedAt, setObservedAt] = useState(initialObservedAt), [notes, setNotes] = useState("");
  const [error, setError] = useState<string>(); const command = useWorkflowCommand();
  useUnsavedWork(Boolean(supplier || url || price || shipping || notes || title !== line.name || quantity !== "1" || unit !== line.unit || tax !== "unknown" || currency !== "EUR" || observedAt !== initialObservedAt), "supplier quote", command.busy || command.uncertain);
  const save = async () => { setError(undefined); try { const body = { bomLineId: line.id, expectedBomLineVersion: line.version, supplier, title, url, packageQuantity: Number(quantity), packageUnit: unit, priceMinor: quotedMinor(price, currency), currency, ...(shipping.trim() ? { shippingMinor: quotedMinor(shipping, currency) } : {}), taxIncluded: tax, observedAt: `${observedAt}T00:00:00.000Z`, validForDays: 30, ...(notes.trim() ? { notes } : {}) }; await command.execute(`${root}/requirement-offers`, "POST", body, (value) => requirementOfferSchema.parse(mutationValue(value, ["id", "version"]))); onSaved(); } catch (failure) { if (!command.error) setError(failure instanceof Error ? failure.message : "The quote was not saved."); } };
  return <form className="workflow-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><h4>Record supplier quote</h4><fieldset disabled={command.busy || command.uncertain} className="correction-fields">
    <label className="form-field"><span>Supplier</span><input required maxLength={240} value={supplier} onChange={(event) => setSupplier(event.target.value)} /></label><label className="form-field"><span>Quoted item</span><input required maxLength={240} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="form-field"><span>Supplier source URL</span><input required type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://supplier.example/item" /></label>
    <div className="form-row"><label className="form-field"><span>Quantity per pack</span><input required type="number" min="0.000001" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label className="form-field"><span>Pack unit</span><select aria-label="Quoted pack unit" value={unit} onChange={(event) => setUnit(event.target.value as typeof unit)}>{["each", "gram", "metre", "millimetre", "millilitre", "set"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="form-row"><label className="form-field"><span>Pack price</span><input required inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="12.50" /></label><label className="form-field"><span>Currency</span><select aria-label="Quoted currency" value={currency} onChange={(event) => setCurrency(event.target.value)}>{["EUR", "GBP", "USD", "AUD", "CAD", "CHF", "DKK", "SEK", "NOK", "JPY"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <label className="form-field"><span>Shipping for this quote, blank if unknown</span><input inputMode="decimal" value={shipping} onChange={(event) => setShipping(event.target.value)} placeholder="Unknown" /></label><label className="form-field"><span>Tax included</span><select aria-label="Quoted tax included" value={tax} onChange={(event) => setTax(event.target.value)}><option value="unknown">Not confirmed</option><option value="yes">Yes</option><option value="no">No</option></select></label><label className="form-field"><span>Observation date</span><input required type="date" value={observedAt} onChange={(event) => setObservedAt(event.target.value)} /></label><label className="form-field"><span>Quote notes</span><textarea maxLength={2000} rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
  </fieldset>{(error || command.error) && <p role="alert" className="form-error">{command.error ?? error}</p>}<div className="dialog-actions"><button type="button" className="button button-quiet" disabled={command.busy || command.uncertain} onClick={onCancel}>Cancel quote</button><button type="submit" className="button button-primary" disabled={command.busy}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged quote" : "Save supplier observation"}</button></div></form>;
}
