import { useState } from "react";
import { requirementOfferSchema, offerChoiceSchema } from "@benchledger/api-contract";
import type { BomLine, RequirementOffer, OfferChoice, RequirementOfferEstimate } from "@benchledger/api-contract";
import type { Project } from "./domain";
import { useWorkflowRead, useWorkflowCommand, mutationValue, quotedMoney, quotedMinor, revisionWorkflowPath } from "./workflow-ui";
interface SourcingRow { line: BomLine; decision: string; missingQuantity: number; offers: RequirementOffer[]; choice: OfferChoice | null; estimate: RequirementOfferEstimate }
interface SourcingPage { data: SourcingRow[]; total: number; nextCursor?: string; totals: Record<string, { knownMinor: number; shippingComplete: boolean; taxesComplete: boolean }>; notice: string }
export function RequirementSourcing({ project, readOnly = false }: { project: Project; readOnly?: boolean }) {
  const [cursor, setCursor] = useState<string>(), [previous, setPrevious] = useState<(string | undefined)[]>([]), [draftFor, setDraftFor] = useState<string>();
  const root = project.serverRevisionId ? revisionWorkflowPath(project.id, project.serverRevisionId) : undefined;
  const source = useWorkflowRead<SourcingPage>(root ? `${root}/sourcing?limit=20${cursor ? `&cursor=${cursor}` : ""}` : undefined, JSON.stringify(project.bom.map((line) => [line.id, line.version])));
  if (!root) return <p>Supplier quotes require a connected project revision.</p>;
  return <section className="surface requirement-sourcing" aria-label="Requirement sourcing"><h2>Supplier quotes for this project</h2><p>Record candidates even when you own none of the required stock. Only explicitly reviewed quotes for required Source gaps enter the estimate. Nothing is purchased here.</p>
    {source.loading && <p role="status">Loading requirement quotes…</p>}{source.error && <p role="alert">{source.error}</p>}
    {source.data && <><div className="sourcing-totals">{Object.entries(source.data.totals).length ? Object.entries(source.data.totals).map(([currency, total]) => <p key={currency}><strong>{quotedMoney(total.knownMinor, currency)}</strong> · {total.shippingComplete ? "recorded shipping included" : "shipping incomplete"} · {total.taxesComplete ? "tax included" : "tax not fully confirmed"}</p>) : <p>No reviewed, current quotes enter the estimate yet.</p>}</div>
      {source.data.data.map((row) => <article className="sourcing-requirement" key={row.line.id}><div className="workflow-section-heading"><h3>{row.line.name}</h3><span>{row.line.optional ? "Optional" : row.decision === "source" ? "Source" : row.decision === "check" ? "Check" : row.decision === "ready" ? "Ready" : "Decide"}</span></div><p>{row.line.requiredQuantity} {row.line.unit} required · {row.missingQuantity} unfilled</p>
        {row.estimate.status === "estimated" ? <p className="estimate-summary">{row.estimate.packages} packs supply {row.estimate.partsSupplied} {row.line.unit} · {quotedMoney(row.estimate.totalMinor!, row.estimate.currency!)} known cost</p> : <p className="form-hint">{row.estimate.reason}</p>}
        {row.offers.length ? row.offers.map((offer) => <QuoteCard key={offer.id} offer={offer} row={row} root={root} readOnly={readOnly || project.status === "archived"} onSaved={source.reload} />) : <p>No supplier observations recorded for this requirement.</p>}
        {!readOnly && project.status !== "archived" && (draftFor === row.line.id ? <QuoteForm line={row.line} root={root} onSaved={() => { setDraftFor(undefined); source.reload(); }} onCancel={() => setDraftFor(undefined)} /> : <button type="button" className="button button-secondary" onClick={() => setDraftFor(row.line.id)}>Record quote for {row.line.name}</button>)}
      </article>)}
      <div className="workflow-pagination"><button type="button" className="button button-quiet" disabled={!previous.length || source.loading} onClick={() => { setCursor(previous.at(-1)); setPrevious((all) => all.slice(0, -1)); }}>Previous requirements</button><span>{source.data.total} requirements</span><button type="button" className="button button-quiet" disabled={!source.data.nextCursor || source.loading} onClick={() => { setPrevious((all) => [...all, cursor]); setCursor(source.data!.nextCursor); }}>Next requirements</button></div>
    </>}
    <button type="button" className="text-button" onClick={source.reload}>Refresh supplier quotes</button>
  </section>;
}
function QuoteCard({ offer, row, root, readOnly, onSaved }: { offer: RequirementOffer; row: SourcingRow; root: string; readOnly: boolean; onSaved(): void }) {
  const [confirmed, setConfirmed] = useState(false); const command = useWorkflowCommand();
  const selected = row.choice?.offerId === offer.id, current = selected && row.choice?.bomLineVersion === row.line.version;
  const choose = async () => { try { await command.execute(`${root}/offer-choice`, "PUT", { bomLineId: row.line.id, offerId: selected && current ? null : offer.id, expectedVersion: row.choice?.version ?? 0, expectedBomLineVersion: row.line.version, confirmedFit: confirmed }, (value) => offerChoiceSchema.parse(mutationValue(value, ["id", "version"]))); onSaved(); } catch { /* state retained for explicit retry */ } };
  return <div className={`quote-card ${selected ? "is-selected" : ""}`}><strong>{offer.supplier}: {offer.title}</strong><p>{quotedMoney(offer.priceMinor, offer.currency)} per pack of {offer.packageQuantity} {offer.packageUnit} · shipping {offer.shippingMinor === undefined ? "not recorded" : quotedMoney(offer.shippingMinor, offer.currency)} · tax {offer.taxIncluded}</p><p>Observed {offer.observedAt.slice(0,10)} · review after {offer.validForDays} days</p>{offer.notes && <p>{offer.notes}</p>}<a href={offer.url} target="_blank" rel="noreferrer noopener">Open recorded supplier source</a>
    {selected && <p>{current ? "Selected for estimate" : "Selected quote needs renewed review because the requirement changed"}</p>}
    {!readOnly && <div className="quote-review-actions">{(!selected || !current) && <label className="check-field"><input type="checkbox" checked={confirmed} disabled={command.busy || command.uncertain} onChange={(event) => setConfirmed(event.target.checked)} /><span>I checked that this quoted item meets the current requirement</span></label>}<button type="button" className="button button-quiet" disabled={command.busy || (!current && !confirmed)} onClick={() => { void choose(); }}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged selection" : current ? "Clear quote selection" : "Use reviewed quote"}</button></div>}
    {command.error && <p role="alert" className="form-error">{command.error}</p>}
  </div>;
}
export function QuoteForm({ line, root, onSaved, onCancel }: { line: BomLine; root: string; onSaved(): void; onCancel(): void }) {
  const [supplier, setSupplier] = useState(""), [title, setTitle] = useState(line.name), [url, setUrl] = useState("");
  const [quantity, setQuantity] = useState("1"), [unit, setUnit] = useState(line.unit), [price, setPrice] = useState(""), [currency, setCurrency] = useState("EUR"), [shipping, setShipping] = useState("");
  const [tax, setTax] = useState("unknown"), [observedAt, setObservedAt] = useState(new Date().toISOString().slice(0,10)), [notes, setNotes] = useState("");
  const [error, setError] = useState<string>(); const command = useWorkflowCommand();
  const save = async () => { setError(undefined); try { const body = { bomLineId: line.id, expectedBomLineVersion: line.version, supplier, title, url, packageQuantity: Number(quantity), packageUnit: unit, priceMinor: quotedMinor(price, currency), currency, ...(shipping.trim() ? { shippingMinor: quotedMinor(shipping, currency) } : {}), taxIncluded: tax, observedAt: `${observedAt}T00:00:00.000Z`, validForDays: 30, ...(notes.trim() ? { notes } : {}) }; await command.execute(`${root}/requirement-offers`, "POST", body, (value) => requirementOfferSchema.parse(mutationValue(value, ["id", "version"]))); onSaved(); } catch (failure) { if (!command.error) setError(failure instanceof Error ? failure.message : "The quote was not saved."); } };
  return <form className="workflow-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><h4>Record supplier quote</h4><fieldset disabled={command.busy || command.uncertain} className="correction-fields">
    <label className="form-field"><span>Supplier</span><input required maxLength={240} value={supplier} onChange={(event) => setSupplier(event.target.value)} /></label><label className="form-field"><span>Quoted item</span><input required maxLength={240} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="form-field"><span>Supplier source URL</span><input required type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://supplier.example/item" /></label>
    <div className="form-row"><label className="form-field"><span>Quantity per pack</span><input required type="number" min="0.000001" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label className="form-field"><span>Pack unit</span><select aria-label="Quoted pack unit" value={unit} onChange={(event) => setUnit(event.target.value as typeof unit)}>{["each", "gram", "metre", "millimetre", "millilitre", "set"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="form-row"><label className="form-field"><span>Pack price</span><input required inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="12.50" /></label><label className="form-field"><span>Currency</span><select aria-label="Quoted currency" value={currency} onChange={(event) => setCurrency(event.target.value)}>{["EUR", "GBP", "USD", "AUD", "CAD", "CHF", "DKK", "SEK", "NOK", "JPY"].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <label className="form-field"><span>Shipping for this quote, blank if unknown</span><input inputMode="decimal" value={shipping} onChange={(event) => setShipping(event.target.value)} placeholder="Unknown" /></label><label className="form-field"><span>Tax included</span><select aria-label="Quoted tax included" value={tax} onChange={(event) => setTax(event.target.value)}><option value="unknown">Not confirmed</option><option value="yes">Yes</option><option value="no">No</option></select></label><label className="form-field"><span>Observation date</span><input required type="date" value={observedAt} onChange={(event) => setObservedAt(event.target.value)} /></label><label className="form-field"><span>Quote notes</span><textarea maxLength={2000} rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
  </fieldset>{(error || command.error) && <p role="alert" className="form-error">{command.error ?? error}</p>}<div className="dialog-actions"><button type="button" className="button button-quiet" disabled={command.busy || command.uncertain} onClick={onCancel}>Cancel quote</button><button type="submit" className="button button-primary" disabled={command.busy}>{command.busy ? "Saving…" : command.uncertain ? "Retry unchanged quote" : "Save supplier observation"}</button></div></form>;
}
