// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, within, waitFor } from "@testing-library/react";
import { WorkbenchHome } from "./workbench-home";
import { projects, inventory } from "./mock-data";
import { homePreferenceKey } from "./workbench-state";
beforeEach(() => { localStorage.clear(); HTMLElement.prototype.scrollIntoView = vi.fn(); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const fixture = (id: string, status: typeof projects[number]["status"] = "planned") => ({ ...structuredClone(projects[0]!), id, name: id, status, fabricationRoute: "none" as const });
const props = () => ({ projects: [fixture("Café fixture"), fixture("Sensor box"), fixture("Finished jig", "complete")], items: inventory, printers: [], sampleMode: false, onOpen: vi.fn(), onTask: vi.fn(), onNewProject: vi.fn(), onAddItem: vi.fn(), onImport: vi.fn(), onInventory: vi.fn(), onItem: vi.fn(), onRefresh: vi.fn(async () => true) });
it("searches, pins and resumes accessible projects using local preferences", async () => {
  localStorage.setItem(homePreferenceKey(false), JSON.stringify({ recent: ["inaccessible-id", "Sensor box"] }));
  const data = props(); render(<WorkbenchHome {...data} />);
  expect(screen.getByRole("heading", { level: 1, name: "Projects" })).toBeTruthy();
  expect(screen.getByLabelText("Resume recent project").textContent).toContain("Sensor box");
  fireEvent.click(screen.getByRole("button", { name: "Resume project" })); expect(data.onOpen).toHaveBeenCalledWith("Sensor box");
  fireEvent.change(screen.getByLabelText("Find a project"), { target: { value: "cafe" } }); expect(document.querySelectorAll(".home-project-row")).toHaveLength(1);
  fireEvent.click(screen.getByRole("button", { name: "Pin project Café fixture" }));
  fireEvent.change(screen.getByLabelText("Find a project"), { target: { value: "" } }); fireEvent.change(screen.getByLabelText("Filter projects"), { target: { value: "pinned" } });
  expect(document.querySelectorAll(".home-project-row")).toHaveLength(1); expect(localStorage.getItem(homePreferenceKey(false))).toContain("Café fixture");
  fireEvent.click(screen.getByRole("button", { name: "Unpin project Café fixture" })); expect(screen.getByText("No projects match this view")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Show all projects" })); expect(document.querySelectorAll(".home-project-row")).toHaveLength(3);
  fireEvent.change(screen.getByLabelText("Sort projects"), { target: { value: "name" } }); expect(document.querySelector(".home-project-name")?.textContent).toContain("Café fixture");
});
it("opens concrete tasks, provides quick entry and preserves refresh failures", async () => {
  const data = props(); data.onRefresh.mockResolvedValue(false); render(<WorkbenchHome {...data} />);
  fireEvent.click(screen.getByRole("button", { name: "New project" })); fireEvent.click(screen.getByRole("button", { name: "Workspace tools" })); fireEvent.click(screen.getByRole("button", { name: "Add inventory" })); fireEvent.click(screen.getByRole("button", { name: "Import requirements" }));
  expect(data.onNewProject).toHaveBeenCalledOnce(); expect(data.onAddItem).toHaveBeenCalledOnce(); expect(data.onImport).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "All next actions" }));
  fireEvent.click(document.querySelector<HTMLButtonElement>(".home-task")!); expect(data.onTask).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "Refresh workspace" })); await screen.findByRole("alert"); expect(document.querySelectorAll(".home-project-row")).toHaveLength(2);
});
it("handles empty, unavailable and long project lists without invented totals", async () => {
  const data = props(); const view = render(<WorkbenchHome {...data} projects={[]} />);
  expect(screen.getByRole("heading", { name: "What would you like to make?" })).toBeTruthy();
  view.rerender(<WorkbenchHome {...data} projects={[{ ...fixture("Unknown"), readinessUnavailable: true }]} />);
  expect(screen.getByText(/Check and sourcing counts exclude those projects/u)).toBeTruthy();
  view.rerender(<WorkbenchHome {...data} projects={Array.from({ length: 18 }, (_, i) => fixture(`Project ${i}`))} />);
  expect(document.querySelectorAll(".home-project-row")).toHaveLength(12); fireEvent.click(screen.getByRole("button", { name: "Show more projects" })); expect(document.querySelectorAll(".home-project-row")).toHaveLength(18);
  expect(screen.queryByLabelText("Workspace task shortcuts")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "All next actions" }));
  fireEvent.change(screen.getByLabelText("Filter attention queue"), { target: { value: "check" } });
  expect((screen.getByLabelText("Filter attention queue") as HTMLSelectElement).value).toBe("check");
  fireEvent.change(screen.getByLabelText("Filter attention queue"), { target: { value: "source" } });
  fireEvent.change(screen.getByLabelText("Filter attention queue"), { target: { value: "all" } });
  fireEvent.change(screen.getByLabelText("Filter projects"), { target: { value: "attention" } });
  fireEvent.change(screen.getByLabelText("Filter projects"), { target: { value: "active" } });
  fireEvent.click(screen.getByRole("button", { name: "Workspace tools" }));
  fireEvent.click(screen.getByRole("button", { name: "Manage inventory" })); expect(data.onInventory).toHaveBeenCalledOnce();
  data.onRefresh.mockRejectedValueOnce(new Error("offline")); fireEvent.click(screen.getByRole("button", { name: "Refresh workspace" })); await waitFor(() => expect(screen.getByRole("alert").textContent).toContain("could not refresh"));
});

it("gives an empty workshop two clear starting paths and keeps supporting tools optional", async () => {
  const data = props(); render(<WorkbenchHome {...data} projects={[]} />);
  expect(screen.queryByRole("region", { name: "Project register" })).toBeNull();
  expect(screen.queryByRole("region", { name: "Workspace attention queue" })).toBeNull();
  expect(screen.queryByText("No open planning checks")).toBeNull();
  expect(screen.getByRole("button", { name: "Workspace tools" }).getAttribute("aria-expanded")).toBe("false");
  expect(screen.queryByRole("button", { name: "New project" })).toBeNull();
  expect(screen.queryByRole("button", { name: "Open inventory" })).toBeNull();
  expect(screen.getAllByRole("button", { name: "Add inventory" })).toHaveLength(1);
  expect(screen.queryByRole("button", { name: "Import requirements" })).toBeNull();
  expect(screen.queryByRole("region", { name: "Workshop equipment" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Start a project" }));
  fireEvent.click(screen.getByRole("button", { name: "Add inventory" }));
  expect(data.onNewProject).toHaveBeenCalledOnce();
  expect(data.onAddItem).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "Workspace tools" }));
  expect(screen.getAllByRole("button", { name: "Add inventory" })).toHaveLength(1);
  fireEvent.click(screen.getByRole("button", { name: "Import requirements" }));
  expect(data.onImport).toHaveBeenCalledOnce();
  fireEvent.click(screen.getByRole("button", { name: "Refresh workspace" }));
  await waitFor(() => expect(screen.getByRole("button", { name: "Refresh workspace" }).hasAttribute("disabled")).toBe(false));
  expect(data.onRefresh).toHaveBeenCalledOnce();
});
it("keeps archived-only and failed refresh states distinct from first use", async () => {
  const data = props();
  const onOpenArchive = vi.fn();
  const view = render(<WorkbenchHome {...data} projects={[]} archivedCount={2} onOpenArchive={onOpenArchive} />);
  expect(screen.getByRole("heading", { name: "No active projects" })).toBeTruthy();
  expect(screen.queryByRole("region", { name: "Getting started" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "View archived projects" }));
  expect(onOpenArchive).toHaveBeenCalledOnce();
  view.rerender(<WorkbenchHome {...data} projects={[]} />);
  data.onRefresh.mockResolvedValueOnce(false);
  fireEvent.click(screen.getByRole("button", { name: "Workspace tools" }));
  fireEvent.click(screen.getByRole("button", { name: "Refresh workspace" }));
  expect(screen.getByRole("heading", { name: "Checking projects…" })).toBeTruthy();
  expect(screen.queryByRole("region", { name: "Getting started" })).toBeNull();
  await screen.findByRole("alert");
  expect(screen.getByRole("heading", { name: "Projects could not be checked" })).toBeTruthy();
  expect(screen.queryByRole("region", { name: "Getting started" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Refresh workspace" }));
  await screen.findByRole("region", { name: "Getting started" });
  expect(screen.queryByRole("alert")).toBeNull();
});
it("keeps project search visible and discloses supporting tools without blocking next actions", () => {
  const data = props(); render(<WorkbenchHome {...data} />);
  expect(screen.getByRole("textbox", { name: "Find a project" })).toBeTruthy();
  expect(screen.getByRole("button", { name: "All next actions" }).getAttribute("aria-expanded")).toBe("false");
  expect(screen.getByRole("button", { name: "Workspace tools" }).getAttribute("aria-expanded")).toBe("false");
  expect(screen.queryByRole("region", { name: "Workspace attention queue" })).toBeNull();
  expect(screen.queryByRole("button", { name: "Import requirements" })).toBeNull();
  const projectRow = screen.getByRole("button", { name: "Open project Café fixture" }).closest("article")!;
  fireEvent.click(within(projectRow).getByRole("button", { name: /: Café fixture$/u }));
  expect(data.onTask).toHaveBeenCalledWith(expect.objectContaining({ projectId: "Café fixture" }));
  expect(screen.getByText(/Search and task counts cover the projects available in this view/u)).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Open inventory" }));
  expect(data.onInventory).toHaveBeenCalledOnce();
});
it("expands a filtered task queue and opens equipment without implying usability", () => {
  const data = props();
  const printer = inventory.find((item) => item.category === "Printers")!;
  render(<WorkbenchHome {...data} projects={Array.from({ length: 10 }, (_, i) => fixture(`Project ${i}`))} printers={[printer]} isPrinterUsable={() => false} />);
  fireEvent.click(screen.getByRole("button", { name: "All next actions" }));
  const queue = screen.getByRole("region", { name: "Workspace attention queue" });
  expect(within(queue).getAllByRole("button", { name: /: Project/u })).toHaveLength(8);
  fireEvent.click(within(queue).getByRole("button", { name: "Show more tasks" }));
  expect(within(queue).getAllByRole("button", { name: /: Project/u }).length).toBeGreaterThan(8);
  fireEvent.change(screen.getByLabelText("Filter attention queue"), { target: { value: "check" } });
  expect(within(queue).getAllByRole("button", { name: /: Project/u }).length).toBeLessThanOrEqual(8);
  fireEvent.click(screen.getByRole("button", { name: "Workspace tools" }));
  expect(screen.getByText("Needs stock or product setup check")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: new RegExp(printer.name, "u") }));
  expect(data.onItem).toHaveBeenCalledWith(printer.id);
});
