import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import AxeBuilder from "@axe-core/playwright";
test("assembly explorer imports CAD, edits a guide, saves and reopens on desktop and mobile", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/"); await page.getByLabel("Workspace password").fill("demo-password-please-change"); await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByRole("button", { name: /^Projects/u }).click(); await page.getByRole("tab", { name: /^Files/u }).click();
  await page.getByLabel("Choose files to upload").setInputFiles({ name: "synthetic-assembly.step", mimeType: "model/step", buffer: await readFile("packages/artifacts/testfiles/synthetic-assembly.step") });
  await page.getByRole("button", { name: "Add 1 file", exact: true }).click(); await expect(page.getByRole("button", { name: "Download synthetic-assembly.step", exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Assembly", exact: true }).click();
  await page.getByLabel("synthetic-assembly.step", { exact: true }).check(); await page.getByRole("button", { name: "Open assembly", exact: true }).click();
  await expect(page.locator(".assembly-canvas canvas")).toBeVisible(); await expect(page.locator(".assembly-dimensions")).toContainText("40.0 × 30.0 × 17.0 mm");
  await page.getByRole("button", { name: "Exploded", exact: true }).click(); await expect(page.getByLabel("Assembly separation")).toHaveValue("100");
  await page.getByRole("button", { name: "Lid", exact: true }).click();
  await page.getByRole("button", { name: "Edit assembly", exact: true }).click();
  await page.getByLabel("Material", { exact: true }).fill("Synthetic cream PLA");
  await page.getByLabel("Fixing notes").fill("Seat the lid after checking the connector clearance.");
  await page.getByLabel("Separation (mm) Z", { exact: true }).fill("45");
  await page.getByRole("button", { name: "Isolate part", exact: true }).click(); await expect(page.getByLabel("Show Base", { exact: true })).not.toBeChecked();
  await page.getByRole("button", { name: "Show all parts", exact: true }).click();
  // LAN HTTP does not expose randomUUID; both local identities must still work.
  await page.evaluate(() => Reflect.deleteProperty(Crypto.prototype, "randomUUID"));
  await page.getByRole("button", { name: "Lid", exact: true }).click();
  await page.getByRole("button", { name: "Add another placement", exact: true }).click();
  await expect(page.getByLabel("Name", { exact: true })).toHaveValue("Lid copy");
  await page.getByRole("button", { name: "Build order", exact: true }).click(); await page.getByRole("button", { name: "Add build step", exact: true }).click();
  await page.getByLabel("Step title").fill("Fit the enclosure"); await page.getByLabel("Instructions", { exact: true }).fill("Check both parts before fastening.");
  await page.getByRole("button", { name: "Save assembly", exact: true }).click(); await expect(page.getByText(/Saved version 1/u)).toBeVisible();
  await page.reload(); await expect(page.getByRole("tab", { name: "Assembly", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.locator(".assembly-canvas canvas")).toBeVisible(); await page.getByRole("button", { name: "Lid", exact: true }).click(); await expect(page.getByText("Synthetic cream PLA", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Build order", exact: true }).click(); await page.getByRole("button", { name: /Fit the enclosure/u }).click();
  await expect(page.getByLabel("Assembly separation")).toHaveValue("55");
  await page.getByRole("button", { name: "Parts & details", exact: true }).click(); await page.getByRole("button", { name: "Show all", exact: true }).click(); await page.getByRole("button", { name: "Exploded", exact: true }).click();
  await page.screenshot({ path: "test-results/assembly-desktop.png", fullPage: true });
  const a11y = await new AxeBuilder({ page }).include(".assembly-workspace").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze(); expect(a11y.violations).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 }); await expect(page.locator(".assembly-canvas canvas")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: "test-results/assembly-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Edit assembly", exact: true }).click(); await page.getByLabel("Assembly name", { exact: true }).fill("Unsaved assembly");
  await page.getByRole("tab", { name: /^Files/u }).click(); await expect(page.getByRole("alertdialog", { name: "Leave without saving?" })).toBeVisible();
});

test("a large assembly keeps selection controls reachable in light, dark and narrow views", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/"); await page.getByLabel("Workspace password").fill("demo-password-please-change"); await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByRole("button", { name: /^Projects/u }).click(); await page.getByRole("tab", { name: /^Files/u }).click();
  await page.getByLabel("Choose files to upload").setInputFiles({ name: "synthetic-panels.step", mimeType: "model/step", buffer: await readFile("packages/artifacts/testfiles/synthetic-assembly.step") });
  await page.getByRole("button", { name: "Add 1 file", exact: true }).click(); await expect(page.getByRole("button", { name: "Download synthetic-panels.step", exact: true })).toBeVisible();
  await page.route("**/assembly", route => route.request().method() === "GET" ? route.fulfill({ json: { assembly: null, warnings: [] } }) : route.abort());
  // Exercise a long list with synthetic repeated placements; never write the mocked draft.
  await page.route("**/assembly/inspect", async route => {
    const response = await route.fetch(), model = await response.json();
    model.parts = Array.from({ length: 26 }, (_, i) => ({ ...model.parts[0], id: `panel-${i}`, name: `Panel ${i + 1}`, position: [i % 5 * 45, Math.floor(i / 5) * 35, 0] }));
    await route.fulfill({ response, json: model });
  });
  await page.getByRole("tab", { name: "Assembly", exact: true }).click();
  await page.getByRole("button", { name: "Select all files", exact: true }).click(); await page.getByRole("button", { name: "Open assembly", exact: true }).click();
  await expect(page.locator(".assembly-canvas canvas")).toBeVisible();
  await expect(page.getByLabel("Assembly name", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Save assembly", exact: true })).toBeVisible();
  expect((await page.locator(".assembly-parts").boundingBox())!.height).toBeLessThanOrEqual(225);
  await page.getByLabel("Find a part", { exact: true }).fill("Panel 26"); await page.getByRole("button", { name: "Panel 26", exact: true }).click();
  await expect(page.getByRole("button", { name: "Isolate part", exact: true })).toBeInViewport();
  await page.getByLabel("Find a part", { exact: true }).fill("");
  await expect(page.getByRole("button", { name: "Isolate part", exact: true })).toBeInViewport();
  const stage = page.locator(".assembly-stage"); const light = await stage.evaluate(el => getComputedStyle(el).backgroundColor);
  await page.evaluate(() => document.documentElement.dataset.theme = "dark");
  await expect.poll(() => stage.evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe(light);
  const darkA11y = await new AxeBuilder({ page }).include(".assembly-workspace").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze(); expect(darkA11y.violations).toEqual([]);
  await page.screenshot({ path: "test-results/assembly-large-dark.png", fullPage: true });
  await page.evaluate(() => document.documentElement.dataset.theme = "light");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByLabel("Assembly separation", { exact: true }).focus(); await page.keyboard.press("ArrowRight"); await expect(page.getByLabel("Assembly separation", { exact: true })).toHaveValue("1");
  await page.screenshot({ path: "test-results/assembly-large-mobile.png", fullPage: true });
});
